spring:
  application:
    name: checkout

    springdoc:
      api-docs:
        path:/v3/api-docs

      swagger-ui:
        path: /swagger-ui.html

        deep-linking: true
        doc-expansion: none
        default-models-expand-depth: -1
        default-model-expand-depth: 1
        default-model-rendering: example
        display-request-duration: true
        filter: true
        tags-sorter: alpha
        operations-sorter: method

        syntax-highlight:
        theme: monokai

        try-it-out-enabled: true
        supported-submit-methods:
              - get
              - post
              - put
              - delete
              - patch

        persist-authorization: true

